### ISSUE TITLE
Do not focus dock

### ISSUE THREAD

**Issue by DavidLGoldberg** [mbuscemi/elm-test-runner#6]
It'd be nice if the dock did not lose your editor's focus.

This is annoying when hitting cmd + t or worse when the run on save option is selected.

I might take a look at fixing this.  Do you agree this is a minor bug and shouldn't be built as an *option*?

Great Job with the package. I love it.  I haven't even started using the seed / generate features yet.

**Comment by mbuscemi** [comment]
Hi, David. Thanks for trying out Elm Test Runner!

This hasn't been an issue for me in my development, but I can see how it would be a nuisance for others. I'll add it to the list for 0.3.0. I also don't see any reason to make an option for this. I'll work on making Atom keep the focus on the text editor. Thanks again!

**Comment by mbuscemi** [comment]
Added to list in #4

**Comment by DavidLGoldberg** [comment]
I time boxed it for 15 minutes or so, couldn't spot where the focus was happening so leaving it to you :)

**Comment by mbuscemi** [comment]
My suspicion is that this is some automatic behavior of Atom that happens when I call "open" on Atom's internal URI for the dock (https://github.com/mbuscemi/elm-test-runner/blob/master/lib/elm-test-runner.js#L117).

My plan is to first find out if Atom supports changing the focus with code (if it doesn't, we're in trouble). And then, if it does, I'll find out if I refocusing after hitting the command key happens fast enough that users won't notice under standard conditions.

**Comment by DavidLGoldberg** [comment]
The focus is definitely a thing ...(activate pane) ...you should be able to
store a reference and restore...

But...I think you should probably open the dock and leave it hidden \ shown
...via dock api...check out what it says about focus ...you shouldn't be
doing open URI each time per se.

**Comment by mbuscemi** [comment]
I have released a fix for this in 0.2.1, which is available now. Is this the desired behavior?

**Comment by DavidLGoldberg** [comment]
Awesome job, thanks!

I keep it open and use the run command it no longer loses focus 👍
